In [2]:
import numpy as np

In [3]:
a = [0, 1, 2, 3, 4, 5]

In [4]:
b = np.array(a) # array로 변경
print(b.dtype, '||', b.ndim, '||', b.shape)

int32 || 1 || (6,)


In [58]:
# 제일 중요한거 먼저

print(np.argmax(b)) # 최댓값의 인덱스 위치

print('~~'*30)

print(np.where( b > 3, 1, 0)) # (조건, 참 값, 거짓 값)

print('~~'*30)

print(np.where(b > 3, 1, b)) # (조건, 참이면 1, 거짓이면 그대로)

print('~~'*30)

print(list(range(1, 10 ,2))) # 2씩 증가, 범위 1 <= x < 10

print('~~'*30)

print(np.linspace(1, 10, 10)) # 범위 1 <= x < 10, 요소의 개수 10
print(np.linspace(1, 10, 20))
print('~~'*30)

5
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[[0 0]
 [0 0]
 [1 1]]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[[0 1]
 [2 3]
 [1 1]]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[1, 3, 5, 7, 9]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


In [20]:
b = b.reshape(3, 2) # 3행 2열로 변경
print(b)

print('~~'*30)

print(b[0,1]) # 첫번째 행, 두 번째 열 요소 조회
print(b[[0,1]]) # 1, 2행 조회

print('~~'*30)

print(b[[0,1], [0, 1]]) # 1행 1열, 2행 2열 요소 조회
# 특이한 점은 각 리스트의 앞 숫자, 뒷 숫자끼리 묶인다는 거임, 리스트끼리 묶이는게 아님

print('~~'*30)

print(b[1:3, 0:3] ) # 2~3행,  1~3열

print('~~'*30)

print(b[1:, 0:2]) # 2~행, 1~3열

[[0 1]
 [2 3]
 [4 5]]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1
[[0 1]
 [2 3]]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[0 3]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[[2 3]
 [4 5]]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[[2 3]
 [4 5]]


In [29]:
print(b[b > 2]) # 2초과 요소 조회

print('~~'*30)

print(b[(b > 2) & (b < 4)]) # 2초과 4미만 요소 조회

[3 4 5]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[3]


In [45]:
c = ([[[ 0,  1,  2,  3], 
       [ 4,  5,  6,  7], 
       [ 8,  9, 10, 11]], 
      
      [[12, 13, 14, 15], 
       [16, 17, 18, 19], 
       [20, 21, 22, 23]]])
c
print(np.sum(c, axis = 1))


[[12 15 18 21]
 [48 51 54 57]]


In [47]:
print(b)
print('~~'*30)
print(np.sum(b, axis = 0)) # 열기준 집계, 일반적인 1차원 행열 방식이 아님 (2차원이기 때문)
# ex) [[[1,2],[3,4]] , [[5,6],[7,8]]] 이러한 4차원 배열에서

# axis = 0 --> [[1,2],[3,4]] -> [[5,6],[7,8]]
# axis = 1 --> [1,2] -> [3,4] 또는 [5,6] -> [7,8]
# axis = 2 --> 1->2 또는 3->4 또는 5->6 또는 7->8

print('~~'*30)
print(np.max(b, axis = 0))
print('~~'*30)
print(np.min(b, axis = 0))
print('~~'*30)
print(np.std(b, axis = 0))
print('~~'*30)
print(np.mean(b, axis = 0))

[[0 1]
 [2 3]
 [4 5]]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[6 9]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[4 5]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[0 1]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[1.63299316 1.63299316]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[2. 3.]
